### ISSUE TITLE
Falling Through World

### ISSUE THREAD

**Issue by watkig2** [VeilbreakerEntertainment/BuildingEscape#1] opened 2018-01-25 23:38 UTC
Video Card: Nvidia Geforce GTX 1050 TI

VRAM: 6GB

Computer: x64 Ailenware

OS: Windows 10 Home

Game Version: 0.0.4-Alpha

Issue: Half the time I bring the sword to the 
rock in the middle of the maze I end up 
teleported and falling through the world.

**Comment by menevia16a** [comment] 2018-01-25 23:56
Hmm, this has not happened on other Windows 10 PCs it's been tested on... And with that graphics it's not your card. It would most likely be caused by the world loading slowly and you being teleported before the ground is actually there. I will adjust the teleport location in the next update, if this was the cause it should fix the issue. I'll keep it open for now.

**Comment by menevia16a** [comment] 2018-01-28 16:13
That commit should hopefully fix your issue, it will be active in v0.0.5-alpha. If it does solve the issue then I will close the issue. Thanks for your feedback. :)

Kind regards,
menevia16a

**Comment by menevia16a** [comment] 2018-01-28 18:42
I was able to reproduce the issue myself and narrowed it down. Without getting into details, it has been fixed in that commit and will be active in v0.0.5-alpha. Thank you for reporting the issue. The issue will now be closed.

Kind regards,
menevia16a

**Closed as completed by menevia16a** 2018-01-28 18:42 UTC
